apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: springboot-helloworld
spec:
  host: springboot-helloworld
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: v1
      labels:
        version: v1